platform :ios, '9.0'

target 'QuickTodo' do
	# 忽略引入库的所有警告（强迫症者的福音啊）
	inhibit_all_warnings!
  use_frameworks!

  pod 'RxSwift', '~> 3.2'
  pod 'RxCocoa', '~> 3.2'
	pod 'RealmSwift', '~> 2.4'
	pod 'RxRealm', '~> 0.5.1'
	pod 'RxDataSources', '~> 1.0.2'
	pod 'Action', '~> 2.2.1'
	pod 'NSObject+Rx', '~> 2.0'
end
