# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

target 'Testing' do
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Hue'
  
  target 'TestingTests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxBlocking'
  end
end

# enable tracing resources
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'RxSwift'
      target.build_configurations.each do |config|
        #config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        if config.name == 'Debug'
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D',
          'TRACE_RESOURCES']
        end
      end
    end
  end
end
