use_frameworks!

abstract_target 'TweetieAbstract' do

    pod 'RxSwift', '3.6'
    pod 'RxCocoa', '3.6'
    pod 'RealmSwift', '2.5'
    pod 'RxRealm', '0.6.0'
    pod 'Unbox', '2.3.0'
    pod 'Then', '2.1.0'
    pod 'Reachability', '3.2.0'
    pod 'Kingfisher', '3.2.2'
    pod 'RxRealmDataSources', '0.2.4'

    target 'Tweetie' do
        pod 'RxDataSources', '1.0.0'
    end
    target 'MacTweetie'
    target 'TweetieTests' do
        pod 'RxTest', '3.1'
    end
end
